image: curlimages/curl:latest

stages:
  - trigger

trigger_CI:
  stage: trigger
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    - curl --request POST --form token=$TUFAST_DV_CI_TOKEN --form "variables[origin]=urinay" --form "variables[msg]=$CI_COMMIT_MESSAGE" --form ref=dev_xb025 "https://gitlab.tufast.de/api/v4/projects/739/trigger/pipeline"